# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appendices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendix',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='appendix',
            name='number',
        ),
    ]
