# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appendices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appendix',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appendix',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subappendix',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subappendix',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subappendix',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
