# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appendices', '0002_auto_20180625_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendix',
            options={'ordering': ['name'], 'verbose_name': 'Appendix', 'verbose_name_plural': 'Appendices'},
        ),
        migrations.AlterModelOptions(
            name='subappendix',
            options={'ordering': ['name'], 'verbose_name': 'Sub-appendix', 'verbose_name_plural': 'Sub-appendices'},
        ),
    ]
