# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-11 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appendices', '0003_auto_20180912_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subappendix',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
