# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appendices', '0006_auto_20181220_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subappendix',
            name='appendix',
        ),
        migrations.DeleteModel(
            name='Appendix',
        ),
        migrations.DeleteModel(
            name='Subappendix',
        ),
    ]
