WEB = 'web'
PDF = 'pdf'

GUIDE_SETTINGS = 'text/{language}/settings.yaml'
GENERATOR_SETTINGS = 'generator/generator-settings.conf'
REGEX_LIST = 'generator/regex-list.conf'
LOGFILE_SETTINGS = 'generator/logging.conf'
PERMISSIONS_LOCATION = 'included-files'
GLOSSARY_LOCATION = 'further-information/glossary.html'
INTERACTIVE_CLASS = 'interactive'
