#!/bin/bash

ERROR='\033[0;31m'
SUCCESS='\033[0;32m'
CODE='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${ERROR}This script is now deprecated.${NC} Use the ${SUCCESS}./dev${NC} script instead."

exit 1
