# Generated by Django 3.2.12 on 2022-05-27 10:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=300)),
                ('object_type_name', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=10)),
                ('result_preview', models.TextField(default='')),
                ('boost', models.FloatField()),
                ('order', models.PositiveSmallIntegerField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='searchitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_sear_search__d3f1fd_gin'),
        ),
    ]
