# Generated by Django 3.2.12 on 2022-05-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchitem',
            options={'ordering': ['order']},
        ),
    ]
