# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('term', models.CharField(max_length=200, null=True, unique=True)),
                ('definition', models.TextField()),
            ],
        ),
    ]
