# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_interactive_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interactive',
        ),
    ]
