# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_delete_interactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryterm',
            options={'ordering': ['term']},
        ),
    ]
