# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_delete_interactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.SmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
