# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_chapter_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['number']},
        ),
    ]
