# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_auto_20171130_2023'),
        ('chapters', '0007_auto_20171201_0146'),
    ]

    operations = [
    ]
