# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0003_remove_interactive_chapter'),
        ('chapters', '0008_merge_20171204_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='interactives',
            field=models.ManyToManyField(null=True, related_name='chapter', to='interactives.Interactive'),
        ),
    ]
