# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_merge_20171204_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('heading', models.CharField(max_length=100)),
                ('number', models.SmallIntegerField(unique=True)),
                ('content', models.TextField()),
                ('next_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='chapters.ChapterSection')),
                ('previous_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='chapters.ChapterSection')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='first_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='chapters.Chapter'),
        ),
    ]
