# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0009_chapter_interactives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='interactives',
            field=models.ManyToManyField(related_name='chapter', to='interactives.Interactive'),
        ),
    ]
