# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0010_auto_20180207_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='introduction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
