# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_chapter_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptersection',
            name='slug',
            field=models.SlugField(),
        ),
    ]
