# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0013_auto_20180222_0802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chaptersection',
            unique_together=set([('number', 'chapter')]),
        ),
    ]
