# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0014_auto_20180222_0806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chaptersection',
            unique_together=set([]),
        ),
    ]
