# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 08:57
from __future__ import unicode_literals

import chapters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0015_auto_20180222_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptersection',
            name='number',
            field=models.SmallIntegerField(),
        ),
    ]
