# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0016_auto_20180222_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='icon',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
