# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0017_auto_20180225_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='other_resources',
        ),
    ]
