# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0018_remove_chapter_other_resources'),
        ('chapters', '0010_auto_20180123_0359'),
    ]

    operations = [
    ]
