# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0020_auto_20180319_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='introduction_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chaptersection',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaptersection',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='chaptersection',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chaptersection',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='term',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
