# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0021_auto_20180319_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='introduction_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='introduction_yy_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='content_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='content_yy_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_xx_lr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_yy_rl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_xx_lr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_yy_rl',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
