# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0022_auto_20180321_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['number'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='chaptersection',
            options={'ordering': ['number'], 'verbose_name': 'Chapter section', 'verbose_name_plural': 'Chapter sections'},
        ),
    ]
