# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0023_auto_20180912_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
