# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-17 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0024_chapter_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.URLField(blank=True, default=''),
        ),
    ]
