# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-11 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0026_auto_20180917_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='introduction_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='content_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='name_de',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_de',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
