# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0029_auto_20181220_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSectionHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(default='', max_length=200)),
                ('language', models.CharField(default='', max_length=10)),
                ('number', models.PositiveSmallIntegerField()),
                ('chapter_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='chapters.ChapterSection')),
            ],
            options={
                'verbose_name': 'Chapter section heading',
                'verbose_name_plural': 'Chapter sections headings',
                'ordering': ['number'],
            },
        ),
    ]
