# Generated by Django 2.2.3 on 2019-10-08 23:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0031_auto_20190626_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chaptersection',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
    ]
