# Generated by Django 2.2.22 on 2021-08-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0032_auto_20191008_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='introduction_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='introduction_yy_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='content_xx_lr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='content_yy_rl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chaptersection',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_xx_lr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_yy_rl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_xx_lr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_yy_rl',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
