# Generated by Django 3.2.12 on 2022-05-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0035_auto_20220527_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptersection',
            options={'ordering': ['chapter__number', 'number'], 'verbose_name': 'chapter section', 'verbose_name_plural': 'chapter sections'},
        ),
    ]
