# Generated by Django 3.2.16 on 2022-11-24 02:49

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0036_alter_chaptersection_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('slug',), name='slug_deferred'),
        ),
    ]
