# Generated by Django 3.2.16 on 2022-11-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0037_chapter_slug_deferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(),
        ),
    ]
