# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_merge_20171204_0325'),
        ('interactives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactives', to='chapters.Chapter'),
        ),
    ]
