# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0002_interactive_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactive',
            name='chapter',
        ),
    ]
