# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0003_remove_interactive_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
