# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0004_interactive_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactive',
            options={'ordering': ['name']},
        ),
    ]
