# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 01:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0005_auto_20180318_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=None),
        ),
        migrations.AddField(
            model_name='interactive',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
