# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0006_auto_20180319_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
