# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0007_auto_20180319_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='name_xx_lr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interactive',
            name='name_yy_rl',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
