# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0008_auto_20180321_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='template_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interactive',
            name='template_xx_lr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interactive',
            name='template_yy_rl',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
