# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0011_auto_20181017_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='name_es',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interactive',
            name='template_es',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
