# Generated by Django 2.2.3 on 2019-11-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0014_auto_20191008_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='use_large_thumbnail',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
