# Generated by Django 2.2.3 on 2019-11-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0015_interactive_use_large_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='use_large_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
