# Generated by Django 3.2.6 on 2021-08-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0015_auto_20210805_0142'),
        ('interactives', '0016_auto_20191129_0012'),
    ]

    operations = [
    ]
