# Generated by Django 3.2.12 on 2022-05-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0018_alter_interactive_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactive',
            options={'ordering': ['name'], 'verbose_name': 'interactive', 'verbose_name_plural': 'interactives'},
        ),
    ]
