# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 09:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=None)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('number', models.SmallIntegerField(unique=True)),
                ('template', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSubpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=None)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpages', to='general.GeneralPage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
