# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalpage',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='generalpage',
            name='number',
        ),
    ]
