// Generated by CoffeeScript 1.10.0
(function() {
  var ALPHABET, decrypt, encrypt, eventStream, keyCodes, shift, singleEvent,
    slice = [].slice,
    modulo = function(a, b) { return (+a % (b = +b) + b) % b; },
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

  keyCodes = {
    BACKSPACE: 8,
    COMMA: 188,
    DELETE: 46,
    DOWN: 40,
    END: 35,
    ENTER: 13,
    ESCAPE: 27,
    HOME: 36,
    LEFT: 37,
    NUMPAD_ADD: 107,
    NUMPAD_DECIMAL: 110,
    NUMPAD_DIVIDE: 111,
    NUMPAD_ENTER: 108,
    NUMPAD_MULTIPLY: 106,
    NUMPAD_SUBTRACT: 109,
    PAGE_DOWN: 34,
    PAGE_UP: 33,
    PERIOD: 190,
    RIGHT: 39,
    SPACE: 32,
    TAB: 9,
    UP: 38
  };

  singleEvent = function() {
    var events, selector;
    selector = arguments[0], events = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    if (selector == null) {
      selector = "document";
    }

    /* Returns a promise for a single event on a single element
        with the event handler supplied by jQuery
     */
    return new Promise(function(resolve) {
      return $(selector).one(events.join(' '), resolve);
    });
  };

  eventStream = function() {
    var events, handler, selector, selectors, subscribers;
    selectors = arguments[0], events = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    if (selectors == null) {
      selectors = "document";
    }

    /* Returns an Observable which can be subscribed to for the given events
        on a given element
     */
    subscribers = new Set();
    if (selectors.join != null) {
      selector = selectors.join(", ");
    } else {
      selector = selectors;
    }
    handler = function(event) {
      return subscribers.forEach(function(subscriber) {
        return subscriber.next(event);
      });
    };
    $(selector).on(events.join(' '), handler);
    return new Observable(function(subscriber) {
      subscribers.add(subscriber);
      return function() {
        return subscribers["delete"](subscriber);
      };
    });
  };

  shift = function(character, rotation) {
    var index, new_index;
    if (rotation == null) {
      rotation = 3;
    }

    /* This shifts a character by rotation characters using the standard
        caesar cipher
     */
    index = ALPHABET.indexOf(character);
    new_index = modulo(index + rotation, ALPHABET.length);
    return ALPHABET[modulo(index + rotation, ALPHABET.length)];
  };

  encrypt = function(text, rotation) {
    var char, i, len, result;
    if (rotation == null) {
      rotation = 3;
    }

    /* Encrypts a piece of text using the Caesar Cipher */
    result = '';
    for (i = 0, len = text.length; i < len; i++) {
      char = text[i];
      if (indexOf.call(ALPHABET, char) >= 0) {
        result += shift(char, rotation);
      } else {
        result += char;
      }
    }
    return result;
  };

  decrypt = function(text, rotation) {
    if (rotation == null) {
      rotation = 3;
    }

    /* Decrypts a piece of text using the Caesar Cipher that was encrypted
        using a given rotation
     */
    return encrypt(text, -rotation);

    /* Filter non-numeric characters from the rotation input */
  };

  eventStream('#interactive-caesar-key-input');

  async.main(function*() {

    /* This endlessly gets button presses and either encrypts or decrypts
        depending on which button was pressed
     */
    var key, original, results;
    results = [];
    while (true) {
      (yield singleEvent('#interactive-caesar-encrypt, #interactive-caesar-decrypt', 'click'));
      key = Number($('#interactive-caesar-key-input').val());
      if ($(event.target).attr('id') === "interactive-caesar-encrypt") {
        original = $('#interactive-caesar-plaintext').val().toUpperCase();
        $('#interactive-caesar-plaintext').val(original);
        results.push($('#interactive-caesar-ciphertext').val(encrypt(original, key)));
      } else {
        original = $('#interactive-caesar-ciphertext').val().toUpperCase();
        $('#interactive-caesar-ciphertext').val(original);
        results.push($('#interactive-caesar-plaintext').val(decrypt(original, key)));
      }
    }
    return results;
  });

}).call(this);
